### ISSUE TITLE
Clients with out-of-sync clocks might cause chronological keys out of order

### ISSUE THREAD

**Issue by folkeinvest-magne** [Skalar/ddes#67]
## Description
At one point it was not possible to commit new events due to version conflicts.
With `retryOnVersionConflict()` it attempted x amount of times before it gave up.
Using MyAggregate.get('key'), returned version 159 as the latest.

Checking the 'events' table directly showed this for the last 2 commits:
```
[
  {
    aggregateType: 'MyType',
    aggregateKey: 'myAggregateKey',
    aggregateVersion: 160,
    chronologicalKey: '20240216095823590:MyType:myAggregateKey:160',
    chronologicalPartition: 'default',
    events: [ [Object] ],
    timestamp: 2024-02-16T09:58:23.590Z,
    expiresAt: null
  },
  {
    aggregateType: 'MyType',
    aggregateKey: 'myAggregateKey',
    aggregateVersion: 159,
    chronologicalKey: '20240216095823593:MyType:myAggregateKey:159',
    chronologicalPartition: 'default',
    events: [ [Object] ],
    timestamp: 2024-02-16T09:58:23.593Z,
    expiresAt: null
  }
]
```
Note the timestamps.
It seems version 160 was committed with a timestamp 3ms before version 159, which caused the chronological key to be out of order.
And every time a new commit happened, it fetched the 'last' one, got 159, attempted `version + 1` and failed. 

This was most likely caused by different replicas of the same api committing at the same time, but with slightly out-of-sync clocks, and `ddes` using Date.now() for timestamps, which in turn is used for chronologicalKey.
[AggregateRoot.ts#L200](https://github.com/Skalar/ddes/blob/master/packages/%40ddes/core/lib/AggregateRoot.ts#L200)

## How to reproduce
Commit events, set local clock back a few seconds and commit new events.

## Possible sollutions
Use a single source of truth for timestamps, the postgres db perhaps?

**Comment by krijoh92** [comment]
It seems like the core issue here isn't the out-of-sync clocks, but rather that the function used by the postgres store to get an aggregate instance used the wrong `ORDER BY` when getting the events for the instance. It was using `ORDER BY timestamp` when it should've been using `ORDER BY aggregate_version`. 

Should be fixed by #68
